# This file is a blueprint for your services on Render.

envVarGroups:
  - name: nft-tracker-secrets # Creates a group to hold our secret
    envVars:
      - key: CRON_SECRET
        generateValue: true # Render will generate a secure, random secret

services:
  # ------------------
  # The Public Web API
  # ------------------
  - type: web
    name: nft-tracker-service # The name of your service
    runtime: node
    region: oregon
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /health # Use the safe /health endpoint for checks
    disk:
      name: nft-data
      mountPath: /data
      sizeGB: 10
    envVarGroups:
      - nft-tracker-secrets # Gives the secret to the web service

  # -------------------------
  # The Scheduled Cron Jobs
  # -------------------------
  - type: cron
    name: hourly-snapshot
    region: oregon
    schedule: "0 * * * *"
    # Add the Authorization header to the command
    command: "curl -X POST https://nft-tracker-service.onrender.com/capture-snapshot -H \"Authorization: Bearer $CRON_SECRET\""
    envVarGroups:
      - nft-tracker-secrets # Gives the secret to this cron job

  - type: cron
    name: daily-processor
    region: oregon
    schedule: "5 0 * * *"
    command: "curl -X POST https://nft-tracker-service.onrender.com/process-daily-events -H \"Authorization: Bearer $CRON_SECRET\""
    envVarGroups:
      - nft-tracker-secrets

  - type: cron
    name: weekly-aggregator
    region: oregon
    schedule: "10 0 * * 1"
    command: "curl -X POST https://nft-tracker-service.onrender.com/aggregate-weekly -H \"Authorization: Bearer $CRON_SECRET\""
    envVarGroups:
      - nft-tracker-secrets

  - type: cron
    name: monthly-aggregator
    region: oregon
    schedule: "15 0 1 * *"
    command: "curl -X POST https://nft-tracker-service.onrender.com/aggregate-monthly -H \"Authorization: Bearer $CRON_SECRET\""
    envVarGroups:
      - nft-tracker-secrets

  - type: cron
    name: yearly-aggregator
    region: oregon
    schedule: "20 0 1 1 *"
    command: "curl -X POST https://nft-tracker-service.onrender.com/aggregate-yearly -H \"Authorization: Bearer $CRON_SECRET\""
    envVarGroups:
      - nft-tracker-secrets
