services:
  # Main web service - KEEP THIS AS IS
  - type: web
    name: nft-tracker-service
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
      - key: API_KEY
        generateValue: true
    disk:
      name: nft-data
      mountPath: /data
      sizeGB: 10

  # Hourly snapshot cron job - FIXED URL
  - type: cron
    name: hourly-snapshot
    env: node
    region: oregon
    schedule: "0 * * * *"
    buildCommand: npm install
    startCommand: "curl -X POST -H 'x-api-key: $API_KEY' https://nft-tracker-service-er83.onrender.com/capture-snapshot"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false

  # Daily processing cron job - FIXED URL
  - type: cron
    name: daily-processor
    env: node
    region: oregon
    schedule: "5 0 * * *"
    buildCommand: npm install
    startCommand: "curl -X POST -H 'x-api-key: $API_KEY' https://nft-tracker-service-er83.onrender.com/process-daily-events"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false

  # Weekly aggregation cron job - FIXED URL
  - type: cron
    name: weekly-aggregator
    env: node
    region: oregon
    schedule: "10 0 * * 1"
    buildCommand: npm install
    startCommand: "curl -X POST -H 'x-api-key: $API_KEY' https://nft-tracker-service-er83.onrender.com/aggregate-weekly"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false

  # Monthly aggregation cron job - FIXED URL
  - type: cron
    name: monthly-aggregator
    env: node
    region: oregon
    schedule: "15 0 1 * *"
    buildCommand: npm install
    startCommand: "curl -X POST -H 'x-api-key: $API_KEY' https://nft-tracker-service-er83.onrender.com/aggregate-monthly"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false

  # Yearly aggregation cron job - FIXED URL
  - type: cron
    name: yearly-aggregator
    env: node
    region: oregon
    schedule: "20 0 1 1 *"
    buildCommand: npm install
    startCommand: "curl -X POST -H 'x-api-key: $API_KEY' https://nft-tracker-service-er83.onrender.com/aggregate-yearly"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false
